// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protobuf/grpcinverter.proto

package ioc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	JobID                uint64   `protobuf:"varint,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Connector            uint64   `protobuf:"varint,3,opt,name=connector,proto3" json:"connector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobID() uint64 {
	if m != nil {
		return m.JobID
	}
	return 0
}

func (m *Job) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Job) GetConnector() uint64 {
	if m != nil {
		return m.Connector
	}
	return 0
}

type Message struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	EOF                  bool     `protobuf:"varint,3,opt,name=EOF,proto3" json:"EOF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Message) GetEOF() bool {
	if m != nil {
		return m.EOF
	}
	return false
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Status struct {
	// Types that are valid to be assigned to Status:
	//	*Status_Ok
	//	*Status_Error
	Status               isStatus_Status `protobuf_oneof:"status"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

type isStatus_Status interface {
	isStatus_Status()
}

type Status_Ok struct {
	Ok *empty.Empty `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type Status_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Status_Ok) isStatus_Status() {}

func (*Status_Error) isStatus_Status() {}

func (m *Status) GetStatus() isStatus_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Status) GetOk() *empty.Empty {
	if x, ok := m.GetStatus().(*Status_Ok); ok {
		return x.Ok
	}
	return nil
}

func (m *Status) GetError() *Error {
	if x, ok := m.GetStatus().(*Status_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Status) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Status_Ok)(nil),
		(*Status_Error)(nil),
	}
}

type Bytes struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{4}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "ioc.Job")
	proto.RegisterType((*Message)(nil), "ioc.Message")
	proto.RegisterType((*Error)(nil), "ioc.Error")
	proto.RegisterType((*Status)(nil), "ioc.Status")
	proto.RegisterType((*Bytes)(nil), "ioc.Bytes")
}

func init() { proto.RegisterFile("pkg/protobuf/grpcinverter.proto", fileDescriptor_9340afc69c44647f) }

var fileDescriptor_9340afc69c44647f = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x4d, 0xb6, 0x49, 0x3f, 0xa6, 0x45, 0x42, 0x16, 0x5a, 0x55, 0x05, 0x44, 0xe5, 0x53, 0x4e,
	0xd9, 0xdd, 0x72, 0x01, 0xad, 0xf6, 0x52, 0x51, 0x68, 0x0b, 0x08, 0xd6, 0x85, 0x0b, 0x27, 0x12,
	0x67, 0x08, 0xa6, 0x6d, 0x26, 0xb2, 0x5d, 0xa4, 0xfe, 0x01, 0x7e, 0x37, 0x8a, 0x13, 0xb4, 0x70,
	0xa8, 0x58, 0xe5, 0x36, 0xf3, 0xfc, 0xde, 0x9b, 0x37, 0x63, 0x78, 0x56, 0x6e, 0xf3, 0x8b, 0x52,
	0x93, 0xa5, 0xf4, 0xf0, 0xed, 0x22, 0xd7, 0xa5, 0x54, 0xc5, 0x4f, 0xd4, 0x16, 0x75, 0xec, 0x50,
	0xd6, 0x51, 0x24, 0x27, 0x8f, 0x73, 0xa2, 0x7c, 0x87, 0x77, 0x44, 0xdc, 0x97, 0xf6, 0x58, 0x33,
	0xf8, 0x2d, 0x74, 0xd6, 0x94, 0xb2, 0x47, 0x10, 0xfe, 0xa0, 0x74, 0xf5, 0x6a, 0xec, 0x4f, 0xfd,
	0x28, 0x10, 0x75, 0xc3, 0xce, 0xa1, 0xbb, 0x47, 0xfb, 0x9d, 0xb2, 0xf1, 0xd9, 0xd4, 0x8f, 0x06,
	0xa2, 0xe9, 0xd8, 0x13, 0x18, 0x48, 0x2a, 0x0a, 0x94, 0x96, 0xf4, 0xb8, 0xe3, 0x14, 0x77, 0x00,
	0xbf, 0x85, 0xde, 0x7b, 0x34, 0x26, 0xc9, 0x91, 0x31, 0x08, 0x52, 0xca, 0x8e, 0xce, 0x75, 0x24,
	0x5c, 0xcd, 0xa6, 0x10, 0xa2, 0xd6, 0xa4, 0x9d, 0xe7, 0x70, 0x06, 0xb1, 0x22, 0x19, 0x2f, 0x2a,
	0x44, 0xd4, 0x0f, 0xec, 0x21, 0x74, 0x16, 0x1f, 0x5e, 0x3b, 0xe3, 0xbe, 0xa8, 0x4a, 0x7e, 0x03,
	0xa1, 0x63, 0x54, 0x86, 0x92, 0x32, 0x74, 0x86, 0x0f, 0x84, 0xab, 0xd9, 0x14, 0x86, 0x19, 0x1a,
	0xa9, 0x55, 0x69, 0x15, 0x15, 0x4d, 0xd4, 0xbf, 0x21, 0xfe, 0x15, 0xba, 0x1b, 0x9b, 0xd8, 0x83,
	0x61, 0x11, 0x9c, 0xd1, 0xd6, 0xa9, 0x87, 0xb3, 0xf3, 0xb8, 0x3e, 0x4c, 0xfc, 0xe7, 0x30, 0xf1,
	0xa2, 0x3a, 0xcc, 0xd2, 0x13, 0x67, 0xb4, 0x65, 0xfc, 0x64, 0xcc, 0xa5, 0xd7, 0x04, 0x9d, 0xf7,
	0xa1, 0x6b, 0x9c, 0x2f, 0x7f, 0x0a, 0xe1, 0xfc, 0x68, 0xd1, 0x54, 0x87, 0x4c, 0xab, 0xa2, 0x59,
	0xb9, 0x6e, 0x66, 0x5b, 0x18, 0xbd, 0xd1, 0xa5, 0x5c, 0x35, 0xbf, 0xc3, 0xae, 0x60, 0xb0, 0xa6,
	0xf4, 0xd3, 0xa1, 0x28, 0x70, 0xc7, 0x4e, 0xe4, 0x98, 0xf4, 0xdd, 0xc8, 0x35, 0xa5, 0xdc, 0xbb,
	0xf4, 0x59, 0x04, 0xc1, 0x47, 0x55, 0x22, 0x1b, 0x39, 0xb4, 0x39, 0xf0, 0xe4, 0x9f, 0x8e, 0x7b,
	0x91, 0x7f, 0xe9, 0xcf, 0x7e, 0x05, 0x30, 0x14, 0xb8, 0x27, 0x8b, 0xcb, 0x63, 0xa6, 0x13, 0x76,
	0x05, 0xbd, 0x55, 0x61, 0x6c, 0xb2, 0x3b, 0x3d, 0xaa, 0xde, 0xce, 0x6d, 0xe0, 0x86, 0xdd, 0xc0,
	0xe0, 0x73, 0xa1, 0xfe, 0x23, 0x3a, 0x81, 0x73, 0x8f, 0xbd, 0x84, 0x70, 0x63, 0x13, 0x6d, 0x5b,
	0x48, 0x5f, 0x40, 0xb0, 0xb1, 0x54, 0xb6, 0x53, 0xbe, 0x55, 0xad, 0xe2, 0x5e, 0x43, 0x4f, 0xa0,
	0x69, 0x19, 0xb8, 0xde, 0xd5, 0x9a, 0x16, 0xd2, 0x18, 0x82, 0x77, 0x94, 0x9b, 0x7b, 0xff, 0x4a,
	0xc5, 0x57, 0xc6, 0xde, 0x97, 0x3f, 0xef, 0x7d, 0x09, 0xe3, 0x6b, 0x45, 0x32, 0xed, 0x3a, 0xe2,
	0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x3d, 0x7b, 0x01, 0x30, 0x04, 0x00, 0x00,
}
