// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protobuf/grpcinverter.proto

package ioc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	JobID                uint64   `protobuf:"varint,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Connector            uint64   `protobuf:"varint,3,opt,name=connector,proto3" json:"connector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobID() uint64 {
	if m != nil {
		return m.JobID
	}
	return 0
}

func (m *Job) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Job) GetConnector() uint64 {
	if m != nil {
		return m.Connector
	}
	return 0
}

type Message struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	EOF                  bool     `protobuf:"varint,3,opt,name=EOF,proto3" json:"EOF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Message) GetEOF() bool {
	if m != nil {
		return m.EOF
	}
	return false
}

type Status struct {
	// Types that are valid to be assigned to Status:
	//	*Status_Ok
	//	*Status_Error
	Status               isStatus_Status `protobuf_oneof:"status"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

type isStatus_Status interface {
	isStatus_Status()
}

type Status_Ok struct {
	Ok *empty.Empty `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type Status_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Status_Ok) isStatus_Status() {}

func (*Status_Error) isStatus_Status() {}

func (m *Status) GetStatus() isStatus_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Status) GetOk() *empty.Empty {
	if x, ok := m.GetStatus().(*Status_Ok); ok {
		return x.Ok
	}
	return nil
}

func (m *Status) GetError() *Error {
	if x, ok := m.GetStatus().(*Status_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Status) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Status_Ok)(nil),
		(*Status_Error)(nil),
	}
}

type Bytes struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{3}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

// The `Status` type defines a logical error model that is suitable for
// different programming environments, including REST APIs and RPC APIs. It is
// used by [gRPC](https://github.com/grpc). Each `Status` message contains
// three pieces of data: error code, error message, and error details.
//
// You can find out more about this error model and how to work with it in the
// [API Design Guide](https://cloud.google.com/apis/design/errors).
type Error struct {
	// The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A developer-facing error message, which should be in English. Any
	// user-facing error message should be localized and sent in the
	// [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// A list of messages that carry the error details.  There is a common set of
	// message types for APIs to use.
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9340afc69c44647f, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "ioc.Job")
	proto.RegisterType((*Message)(nil), "ioc.Message")
	proto.RegisterType((*Status)(nil), "ioc.Status")
	proto.RegisterType((*Bytes)(nil), "ioc.Bytes")
	proto.RegisterType((*Error)(nil), "ioc.Error")
}

func init() { proto.RegisterFile("pkg/protobuf/grpcinverter.proto", fileDescriptor_9340afc69c44647f) }

var fileDescriptor_9340afc69c44647f = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x63, 0x3b, 0x4e, 0x26, 0x39, 0xa0, 0x55, 0x55, 0x99, 0x00, 0x22, 0xf2, 0xc9, 0x27,
	0xb7, 0x35, 0x17, 0x50, 0xc5, 0x81, 0x88, 0x40, 0x12, 0x40, 0xd0, 0x0d, 0x5c, 0x38, 0xe1, 0x8f,
	0xc1, 0x98, 0x24, 0x1e, 0x6b, 0x77, 0x83, 0xe4, 0x3f, 0xc0, 0xef, 0x46, 0x5e, 0x3b, 0xaa, 0x00,
	0x45, 0xad, 0x7c, 0x9b, 0x8f, 0xf7, 0xde, 0xcc, 0x9b, 0x81, 0xa7, 0xe5, 0x36, 0xbb, 0x28, 0x05,
	0x29, 0x8a, 0x0f, 0xdf, 0x2f, 0x32, 0x51, 0x26, 0x79, 0xf1, 0x0b, 0x85, 0x42, 0x11, 0xe8, 0x2a,
	0x33, 0x73, 0x4a, 0xa6, 0x8f, 0x32, 0xa2, 0x6c, 0x87, 0xb7, 0x40, 0xdc, 0x97, 0xaa, 0x6a, 0x10,
	0xd3, 0x87, 0xff, 0x36, 0xa3, 0xa2, 0x6d, 0x79, 0x37, 0x60, 0xae, 0x29, 0x66, 0x67, 0x60, 0xff,
	0xa4, 0x78, 0xf5, 0xda, 0x35, 0x66, 0x86, 0x6f, 0xf1, 0x26, 0x61, 0xe7, 0x30, 0xd8, 0xa3, 0xfa,
	0x41, 0xa9, 0xdb, 0x9f, 0x19, 0xfe, 0x88, 0xb7, 0x19, 0x7b, 0x0c, 0xa3, 0x84, 0x8a, 0x02, 0x13,
	0x45, 0xc2, 0x35, 0x35, 0xe3, 0xb6, 0xe0, 0xdd, 0x80, 0xf3, 0x01, 0xa5, 0x8c, 0x32, 0x64, 0x0c,
	0xac, 0x98, 0xd2, 0x4a, 0xab, 0x4e, 0xb8, 0x8e, 0xd9, 0x0c, 0x6c, 0x14, 0x82, 0x84, 0xd6, 0x1c,
	0x87, 0x10, 0xe4, 0x94, 0x04, 0x8b, 0xba, 0xc2, 0x9b, 0x06, 0x7b, 0x00, 0xe6, 0xe2, 0xe3, 0x1b,
	0x2d, 0x3c, 0xe4, 0x75, 0xe8, 0x7d, 0x83, 0xc1, 0x46, 0x45, 0xea, 0x20, 0x99, 0x0f, 0x7d, 0xda,
	0x6a, 0xbd, 0x71, 0x78, 0x1e, 0x34, 0xbe, 0x82, 0xa3, 0xaf, 0x60, 0x51, 0x9b, 0x5e, 0xf6, 0x78,
	0x9f, 0xb6, 0xcc, 0x3b, 0x39, 0x67, 0xd9, 0x6b, 0x27, 0xcd, 0x87, 0x30, 0x90, 0x5a, 0xd7, 0x7b,
	0x02, 0xf6, 0xbc, 0x52, 0x28, 0xeb, 0x4b, 0xc4, 0x75, 0xd0, 0xee, 0xdc, 0x24, 0x1e, 0x82, 0xad,
	0xa9, 0xb5, 0xa3, 0x84, 0x52, 0xd4, 0x5d, 0x9b, 0xeb, 0x98, 0xb9, 0xe0, 0xec, 0x1b, 0xc3, 0xed,
	0x9d, 0x8e, 0x29, 0x0b, 0xc0, 0x49, 0x51, 0x45, 0xf9, 0x4e, 0xba, 0xe6, 0xcc, 0xf4, 0xc7, 0xe1,
	0xd9, 0x7f, 0x2b, 0xbf, 0x2a, 0x2a, 0x7e, 0x04, 0x85, 0x5b, 0x98, 0xbc, 0x15, 0x65, 0xb2, 0x6a,
	0x1f, 0xcc, 0xae, 0x60, 0xb4, 0xa6, 0xf8, 0xf3, 0xa1, 0x28, 0x70, 0xc7, 0x4e, 0xd8, 0x9d, 0x0e,
	0xb5, 0xb3, 0x35, 0xc5, 0x5e, 0xef, 0xd2, 0x60, 0x3e, 0x58, 0x9f, 0xf2, 0x12, 0xd9, 0x44, 0x57,
	0xdb, 0x47, 0x4c, 0xff, 0xca, 0xbc, 0x9e, 0x6f, 0x5c, 0x1a, 0xe1, 0x6f, 0x0b, 0xc6, 0x1c, 0xf7,
	0xa4, 0x70, 0x59, 0xa5, 0x22, 0x62, 0x57, 0xe0, 0xac, 0x0a, 0xa9, 0xa2, 0xdd, 0xe9, 0x51, 0xcd,
	0x11, 0xf5, 0xa1, 0xf4, 0xb0, 0x97, 0x30, 0xfa, 0x52, 0xe4, 0x77, 0x90, 0x4e, 0xd4, 0xbd, 0x1e,
	0x7b, 0x01, 0xf6, 0x46, 0x45, 0x42, 0x75, 0xa0, 0x3e, 0x07, 0x6b, 0xa3, 0xa8, 0xec, 0xc6, 0x7c,
	0x97, 0x77, 0x5a, 0xf7, 0x1a, 0x1c, 0x8e, 0xb2, 0xe3, 0xc2, 0x8d, 0x57, 0x25, 0x3b, 0x50, 0x03,
	0xb0, 0xde, 0x53, 0x26, 0xef, 0xfd, 0x95, 0x1a, 0x9f, 0x4b, 0x75, 0x5f, 0xfc, 0xdc, 0xf9, 0x6a,
	0x07, 0xd7, 0x39, 0x25, 0xf1, 0x40, 0x03, 0x9f, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x1f,
	0x82, 0xf9, 0x73, 0x04, 0x00, 0x00,
}
